packages:
  - examples/**
catalogs:
  dev:
    "@luxass/eslint-config": ^5.0.0
    "@nuxt/kit": ^3.17.5
    "@nuxt/schema": ^3.17.5
    "@rspack/core": ^1.3.15
    "@types/node": ^22.9.0
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
    esbuild: ^0.25.5
    eslint: ^9.29.0
    rolldown: 1.0.0-beta.19
    rollup: ^4.44.0
    tsup: ^8.5.0
    typescript: ^5.8.3
    vite: ^7.0.0
    vitest: ^3.2.4
    vitest-testdirs: ^4.0.1
    webpack: ^5.99.9

  example:
    "@rspack/cli": 1.3.15
    "@rspack/plugin-react-refresh": ^1.4.3
    "@tailwindcss/vite": ^4.1.10
    "@vitejs/plugin-react": ^4.5.2
    react: ^19.1.0
    react-dom: ^19.1.0
    react-refresh: ^0.17.0
    ts-node: ^10.9.2

  prod:
    git-url-parse: ^16.1.0
    simple-git: ^3.28.0
    unplugin: ^2.3.5

onlyBuiltDependencies:
  - esbuild
