packages:
  - examples/**

overrides:
  rolldown: catalog:dev

catalogs:
  dev:
    "@luxass/eslint-config": ^7.2.0
    "@nuxt/kit": ^4.3.1
    "@nuxt/schema": ^4.3.1
    "@rspack/core": ^1.7.6
    "@types/node": ^24.10.0
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
    esbuild: ^0.27.3
    eslint: ^9.39.2
    publint: ^0.3.17
    rolldown: ^1.0.0-rc.4
    rollup: ^4.57.1
    tsdown: ^0.20.3
    typescript: ^5.9.3
    vite: ^7.3.1
    vitest: ^4.0.18
    vitest-testdirs: ^4.4.2
    webpack: ^5.105.2

  example:
    "@rspack/cli": ^1.7.6
    "@rspack/plugin-react-refresh": ^1.6.1
    "@tailwindcss/vite": ^4.1.18
    "@vitejs/plugin-react": ^5.1.4
    react: ^19.2.4
    react-dom: ^19.2.4
    react-refresh: ^0.18.0
    ts-node: ^10.9.2

  prod:
    git-url-parse: ^16.1.0
    simple-git: ^3.31.1
    unplugin: ^3.0.0

onlyBuiltDependencies:
  - esbuild
