packages:
  - examples/**
catalogs:
  dev:
    "@luxass/eslint-config": ^5.2.5
    "@nuxt/kit": ^4.0.2
    "@nuxt/schema": ^4.0.2
    "@rspack/core": ^1.4.11
    "@types/node": ^22.9.0
    "@types/react": ^19.1.9
    "@types/react-dom": ^19.1.7
    esbuild: ^0.25.8
    eslint: ^9.32.0
    rolldown: 1.0.0-beta.30
    rollup: ^4.46.2
    tsup: ^8.5.0
    typescript: ^5.9.2
    vite: ^7.0.6
    vitest: ^3.2.4
    vitest-testdirs: ^4.0.1
    webpack: ^5.101.0

  example:
    "@rspack/cli": 1.4.11
    "@rspack/plugin-react-refresh": ^1.4.3
    "@tailwindcss/vite": ^4.1.11
    "@vitejs/plugin-react": ^4.7.0
    react: ^19.1.1
    react-dom: ^19.1.1
    react-refresh: ^0.17.0
    ts-node: ^10.9.2

  prod:
    git-url-parse: ^16.1.0
    simple-git: ^3.28.0
    unplugin: ^2.3.5

onlyBuiltDependencies:
  - esbuild
