packages:
  - examples/**
catalogs:
  dev:
    "@luxass/eslint-config": 6.0.1
    "@nuxt/kit": 4.2.0
    "@nuxt/schema": 4.2.0
    "@rspack/core": 1.5.8
    "@types/node": 22.18.3
    "@types/react": 19.2.2
    "@types/react-dom": 19.2.2
    esbuild: 0.25.11
    eslint: 9.38.0
    rolldown: 1.0.0-beta.45
    rollup: 4.52.5
    tsup: 8.5.0
    typescript: 5.9.3
    vite: 7.1.12
    vitest: 4.0.4
    vitest-testdirs: 4.3.0
    webpack: 5.102.1

  example:
    "@rspack/cli": 1.5.8
    "@rspack/plugin-react-refresh": 1.5.2
    "@tailwindcss/vite": 4.1.16
    "@vitejs/plugin-react": 5.1.0
    react: 19.2.0
    react-dom: 19.2.0
    react-refresh: 0.18.0
    ts-node: 10.9.2

  prod:
    git-url-parse: 16.1.0
    simple-git: 3.28.0
    unplugin: 2.3.10

onlyBuiltDependencies:
  - esbuild
