ignoreScripts: true
catalogMode: prefer
minimumReleaseAge: 5760
trustPolicy: no-downgrade
strictDepBuilds: true
blockExoticSubdeps: true
shellEmulator: true
packages:
  - examples/**

overrides:
  rolldown: catalog:dev

catalogs:
  dev:
    "@luxass/eslint-config": ^7.3.0
    "@nuxt/kit": ^4.4.2
    "@nuxt/schema": ^4.4.2
    "@rspack/core": ^1.7.10
    "@types/node": ^24.10.0
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3
    esbuild: ^0.27.4
    eslint: ^10.1.0
    publint: ^0.3.18
    rolldown: ^1.0.0-rc.12
    rollup: ^4.60.0
    tsdown: ^0.21.5
    typescript: ^6.0.2
    vite: ^8.0.3
    vitest: ^4.1.2
    vitest-testdirs: ^4.4.3
    webpack: ^5.105.4

  example:
    "@rspack/cli": ^1.7.10
    "@rspack/plugin-react-refresh": ^1.6.1
    "@vitejs/plugin-react": ^6.0.1
    react: ^19.2.4
    react-dom: ^19.2.4
    react-refresh: ^0.18.0
    ts-node: ^10.9.2

  prod:
    git-url-parse: ^16.1.0
    simple-git: ^3.33.0
    unplugin: ^3.0.0

onlyBuiltDependencies:
  - esbuild
