packages:
  - examples/**
catalogs:
  dev:
    "@luxass/eslint-config": 5.3.2
    "@nuxt/kit": 4.1.2
    "@nuxt/schema": 4.1.2
    "@rspack/core": 1.5.3
    "@types/node": 22.18.3
    "@types/react": 19.1.13
    "@types/react-dom": 19.1.9
    esbuild: 0.25.9
    eslint: ^9.35.0
    rolldown: 1.0.0-beta.37
    rollup: 4.50.1
    tsup: 8.5.0
    typescript: 5.9.2
    vite: 7.1.7
    vitest: 3.2.4
    vitest-testdirs: 4.2.1
    webpack: 5.101.3

  example:
    "@rspack/cli": 1.5.3
    "@rspack/plugin-react-refresh": 1.5.1
    "@tailwindcss/vite": 4.1.13
    "@vitejs/plugin-react": 5.0.4
    react: 19.1.1
    react-dom: 19.1.1
    react-refresh: 0.17.0
    ts-node: 10.9.2

  prod:
    git-url-parse: 16.1.0
    simple-git: 3.28.0
    unplugin: 2.3.10

onlyBuiltDependencies:
  - esbuild
