packages:
  - examples/**
catalogs:
  dev:
    "@luxass/eslint-config": ^5.3.0
    "@nuxt/kit": ^4.0.3
    "@nuxt/schema": ^4.0.3
    "@rspack/core": ^1.5.1
    "@types/node": ^22.9.0
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    esbuild: ^0.25.9
    eslint: ^9.34.0
    rolldown: 1.0.0-beta.34
    rollup: ^4.49.0
    tsup: ^8.5.0
    typescript: ^5.9.2
    vite: ^7.1.3
    vitest: ^3.2.4
    vitest-testdirs: ^4.2.0
    webpack: ^5.101.3

  example:
    "@rspack/cli": 1.5.1
    "@rspack/plugin-react-refresh": ^1.5.0
    "@tailwindcss/vite": ^4.1.12
    "@vitejs/plugin-react": ^5.0.2
    react: ^19.1.1
    react-dom: ^19.1.1
    react-refresh: ^0.17.0
    ts-node: ^10.9.2

  prod:
    git-url-parse: ^16.1.0
    simple-git: ^3.28.0
    unplugin: ^2.3.9

onlyBuiltDependencies:
  - esbuild
